// This file contains the weighted network of coappearances of characters in

var miserables = {
  nodes:[
    {nodeName:"Pavlou, Paul", group:16},
    {nodeName:"Bontis, Nick", group:2},
    {nodeName:"Polakis, Paul", group:1},
    {nodeName:"Diamantopoulos, Adamantios", group:15},
    {nodeName:"Ischiropoulos, Harry", group:1},
    {nodeName:"Dimopoulos, Savas", group:1},
    {nodeName:"Vlassara, Helen", group:1},
    {nodeName:"Triandis, Harry C.", group:1},
    {nodeName:"Spano, Frank C.", group:1},
    {nodeName:"Klironomos, John", group:2},
    {nodeName:"Stamatakis, Alexandros", group:8},
    {nodeName:"Simopoulos, Artemis P.", group:1},
    {nodeName:"Frangogiannis, Nikolaos G.", group:1},
    {nodeName:"Xantheas, Sotiris S.", group:1},
    {nodeName:"Demerouti, Evangelia", group:12},
    {nodeName:"Melis, Anastasios", group:1},
    {nodeName:"Lovinger, Andrew J.", group:1},
    {nodeName:"Alexandridis, Paschalis", group:1},
    {nodeName:"Kouzarides, Tony", group:10},
    {nodeName:"Jonides, John", group:1},
    {nodeName:"Hajishengallis, George", group:1},
    {nodeName:"Bertsekas, Dimitri", group:1},
    {nodeName:"Biliaderis, Costas G.", group:3},
    {nodeName:"Kalogirou, Soteris A.", group:7},
    {nodeName:"Comninellis, Christos", group:5},
    {nodeName:"Yannakakis, Mihalis", group:1},
    {nodeName:"Petrides, Michael", group:2},
    {nodeName:"Pappas, Peter G.", group:1},
    {nodeName:"Terzopoulos, Demetri", group:1},
    {nodeName:"Georgopoulos, Apostolos P.", group:1},
    {nodeName:"Manolagas, Stavros C.", group:1},
    {nodeName:"Christakis, Nicholas A.", group:1},
    {nodeName:"Kitanidis, Peter K.", group:1},
    {nodeName:"Kostarelos, Kostas", group:10},
    {nodeName:"Marmarou, Anthony", group:1},
    {nodeName:"Karypis, George", group:1},
    {nodeName:"Nicolelis, Miguel A.L.", group:1},
    {nodeName:"Tsimikas, Sotirios", group:1},
    {nodeName:"Fokas, A. S.", group:10},
    {nodeName:"Gregoriadis, Gregory", group:10},
    {nodeName:"Aifantis, Elias C.", group:13},
    {nodeName:"Tsitsiklis, John N.", group:1},
    {nodeName:"Maniatis, Tom", group:1},
    {nodeName:"Hadziyannis, Stephanos", group:3},
    {nodeName:"Roukos, Dimitrios H.", group:3},
    {nodeName:"Efstathiou, George", group:10},
    {nodeName:"Sedikides, Constantine", group:10},
    {nodeName:"Antoniadis, Ignatios", group:9},
    {nodeName:"Panagiotopoulos, Athanassios Z.", group:1},
    {nodeName:"Christopoulos, Arthur", group:4},
    {nodeName:"Michalopoulos, George K.", group:1},
    {nodeName:"Demetri, George D.", group:1},
    {nodeName:"Platanias, Leonidas C.", group:1},
    {nodeName:"Manolio, Teri A.", group:1},
    {nodeName:"Giannelis, Emmanuel", group:1},
    {nodeName:"Alexopoulos, George S.", group:1},
    {nodeName:"Poulos, Thomas L.", group:1},
    {nodeName:"Bikiaris, Dimitrios", group:3},
    {nodeName:"Papadimitriou, Christos H.", group:1},
    {nodeName:"Varandas, A. J.C.", group:6},
    {nodeName:"Tsallis, Constantino", group:14},
    {nodeName:"Benetos, Athanase", group:9},
    {nodeName:"Logothetis, Nikos K.", group:10},
    {nodeName:"Kaxiras, Efthimios", group:1},
    {nodeName:"Santamouris, Mattheos", group:4},
    {nodeName:"Tassiulas, Leandros", group:1},
    {nodeName:"Davatzikos, Christos", group:1},
    {nodeName:"Kalivas, Peter W.", group:1},
    {nodeName:"Stephanopoulos, Gregory", group:1},
    {nodeName:"Theoharides, Theoharis C.", group:1},
    {nodeName:"Païdoussis, Michael P.", group:2},
    {nodeName:"Yancopoulos, George D.", group:1},
    {nodeName:"Avouris, Phaedon", group:1},
    {nodeName:"Alivisatos, A. Paul", group:1},
    {nodeName:"Kahrilas, Peter J.", group:1},
    {nodeName:"Floudas, Christodoulos A.", group:1},
  ],
  links:[
    {source:3, target:16, value:10.1},
    {source:3, target:2, value:12.0},
    {source:3, target:1, value:12.1},
    {source:3, target:15, value:13.7},
    {source:3, target:1, value:13.9},
    {source:3, target:1, value:13.9},
    {source:3, target:1, value:14.1},
    {source:3, target:1, value:14.4},
    {source:3, target:1, value:14.4},
    {source:3, target:2, value:14.8},
    {source:3, target:8, value:17.0},
    {source:3, target:1, value:17.2},
    {source:3, target:1, value:17.3},
    {source:3, target:1, value:17.5},
    {source:3, target:12, value:17.8},
    {source:3, target:1, value:18.2},
    {source:3, target:1, value:18.7},
    {source:3, target:1, value:18.8},
    {source:3, target:10, value:18.9},
    {source:3, target:1, value:18.9},
    {source:3, target:1, value:18.9},
    {source:3, target:1, value:18.9},
    {source:3, target:3, value:19.9},
    {source:3, target:7, value:20.4},
    {source:3, target:5, value:21.2},
    {source:3, target:1, value:21.7},
    {source:3, target:2, value:21.9},
    {source:3, target:1, value:22.7},
    {source:3, target:1, value:22.9},
    {source:3, target:1, value:23.2},
    {source:3, target:1, value:23.8},
    {source:3, target:1, value:23.9},
    {source:3, target:1, value:23.9},
    {source:3, target:10, value:24.3},
    {source:3, target:1, value:25.1},
    {source:3, target:1, value:25.9},
    {source:3, target:1, value:27.2},
    {source:3, target:1, value:27.3},
    {source:3, target:10, value:27.5},
    {source:3, target:10, value:27.8},
    {source:3, target:13, value:27.8},
    {source:3, target:1, value:27.9},
    {source:3, target:1, value:28.1},
    {source:3, target:3, value:29.1},
    {source:3, target:3, value:29.2},
    {source:3, target:10, value:29.3},
    {source:3, target:10, value:30.1},
    {source:3, target:9, value:31.6},
    {source:3, target:1, value:31.9},
    {source:3, target:4, value:32.0},
    {source:3, target:1, value:32.8},
    {source:3, target:1, value:33.2},
    {source:3, target:1, value:33.4},
    {source:3, target:1, value:33.6},
    {source:3, target:1, value:33.7},
    {source:3, target:1, value:33.8},
    {source:3, target:1, value:33.8},
    {source:3, target:3, value:34.3},
    {source:3, target:1, value:37.5},
    {source:3, target:6, value:38.0},
    {source:3, target:14, value:38.7},
    {source:3, target:9, value:38.8},
    {source:3, target:10, value:40.0},
    {source:3, target:1, value:40.7},
    {source:3, target:4, value:41.0},
    {source:3, target:1, value:41.5},
    {source:3, target:1, value:42.7},
    {source:3, target:1, value:43.1},
    {source:3, target:1, value:43.7},
    {source:3, target:1, value:43.9},
    {source:3, target:2, value:44.9},
    {source:3, target:1, value:45.1},
    {source:3, target:1, value:45.6},
    {source:3, target:1, value:46.9},
    {source:3, target:1, value:47.7},
    {source:3, target:1, value:49.1},
  ]
};

